* 5回目のレポート (予定)

- 標本の分布の説明 (図解と解説)

  大数の法則，中心極限定理，確率収束，標本平均，標本分散 などを用いて
  
- 標本と点推定の原理
  
  標本分布，一致性，不偏性 など
    
- 信頼区間の推定の原理 (図解と解説)

   標本標準誤差など

- 検定の原理 (図解と解説),

  帰無仮説と対立仮説，第一，第二の過誤，検出力，帰無分布 など

- 各種検定方法の原理

* 4回目のレポート

6章，7章，8章の章末問題を，Rを用いて解いてください。


* 3回目のレポート

** 1. 信頼区間の推定

教科書4章の章末問題，問1， 問3， 問4 を解くRのプログラムを作成し，プロ
グラムと実行結果を一つのファイルにして，Webclass にアップ
してください。

** 2.カイ二乗分布とF分布 (4問)

教科書5章の章末問題に解答してください。
一つのファイルにして，Webclass にアップしてください。
手書，pdf，html, Rmd, などでお願いします。

* 2回目のレポート

  それぞれの問題の -1. では，Rのプログラムを作成し，実行し，結果のグラフ
  を生成し， -2.はレポート用紙の写真かpdfで作成し，
  問題ごとに，一つのファイルにして，Webclass にアップしてください。
  
  http://wiki.cis.iwate-u.ac.jp/~suzuki/bio_stat/org/R-text-3.html を
  参考にしてください。

** 1. 標本平均が従う分布

    1-1. (Rプログラム) 正規分布の母集団から標本を生成し，標本平均の平均と分散を計算し，
         標本平均の頻度表と対応する分布のグラフを重ね描きしてください。

    1-2. 標本平均が従う確率分布と標本平均の標準誤差を示してください。
       
** 2. 標本不偏分散が従う分布

    2-1. (Rプログラム) 正規分布の母集団から標本を生成し，標本不偏分散を
       計算し，標本不偏分散の頻度分布と対応する分布のグラフを重ね描き
       してください。

    2-2. (n-1)*標本不偏分散/母分散 が従う分布を示してください。



