#+OPTIONS: tex:t 
#+include: R-text-common.org
#+Title:   第6章 仮説検定と検出力
#+property: header-args:R :session *rtext* :results output :exports both

入門統計学-第6章のスライドから

* (本章と次章で)仮説検定を学ぶと  何を検証できる?

- 病気かどうかの判断
- 薬の効き目の有無
- 機械導入効果の有無

- 特定の値と標本平均を比較したり，
- 処理前後の 標本平均を比較することで，
  その背後にある母集団の平にも差があるか否かを判定できる
- 平均だけで なく分散なども比較できる
     
** 仮説検定の長所

- 点推定や区間推定は，あくまで推 定量や誤差を数値で表すだけ

  統計学を学んでない人にはわかりにくい

- 仮説検定ならば「処理の効果がある!」とはっきりいえるため，

  誰にでもわかりやすく伝えられるで，結局，この薬は効くの かしら?  白黒
  はっきりして，わかりやす い!
      
** 仮説検定と検出力
仮説検定:母集団に対して主張したくない 仮説(処理の効果がない等)を立て，その 仮説が間違いであることを，実験結果の起 き難ささから判断する。
検出力:母集団の特性に差があるときに， ちゃんと“差がある”と判断できる能力。検定 の性能を表す指標で近年重視されている。
  
* 6.1 検定の概要

1. 仮説の設定:つまらない仮説(帰無仮説)を立てる
2. 検定統計量の計算:実験データから求める
3. 確率の計算:実験結果の起こりやすさ(確率)を求める
4  仮説の判定
   - 4.1 仮説は正しい
       よく起きることが起きただ
   - 4.2 仮説は間違い
       滅多に起きないことが起きた
       棄却
 
* 仮説検定の大まかな手順

- 手順1 :: 仮説の設定

  母集団における未知の事実を説明するため，とりあえず正しいものと仮定し
  ておく道筋を立てる

- 手順2 :: 検定統計量の計算

  観測されたデータのままでは検定できるこ とは少ないので，目的に沿った
  検定のため の統計量を求める (ただし，本章ではこの手順をスキップでき
  る基本的な検定から解説する)
  
- 手順3 :: 確率の計算

  仮説が正しい下での実験結果の起こりやすさ(確率)を計算。

  実際には，確率計算は難しいので，仮説の分布のどれぐらい端の方に位置し
  ているのかで仮説の是非を判定

- 手順4 :: 仮説の判定

  滅多に起きないことが起きたといえるぐらい 確率が低いならば，そもそも
  仮説が間違い だったと判断。そうでなければ判定を保留す る(仮説が正し
  かったとはいわない)
 

* 6.2 仮説の設定  (手順1の説明から)

母集団に立てる仮説には， * 帰無仮説 (H0) *と * 対立仮説 (H1) *の2つがある

- 基本となるのは帰無仮説で，帰無仮説が棄却されたときに採択する仮説が対立
  仮説

帰無仮説は「主張したい内容とは逆の，つまらない内容」とする

- 例 :: 処理効果が無い (2群の母平均に差は無い)

  なぜ主張したい内容としないのだろうか?
     
帰無仮説の内容

- 例 :: 殺虫剤の効果を検定する場合

  主張したいのは「使用効果がある (使用前後で害虫数に差がある)」という内
  容だが...

  それを検証するためには「*匹減る」と具体的にわかってなけれならない (無
  限に設定できる)

  使用効果がない(全く減らない)としておけば，それと矛盾した結果が観測さ
  れれば，効果があるといえる (* 背理法 *)
  
* 6.3 (1標本の)母平均の検定 

検定統計量が不要(容易)な検定から学びます

- 特定の既知の値と観測された標本平均とを比較し，

  - その差が偶然(誤差)の範囲内なのか，

  - 母集団においても差があるといえるほど大きい差なのかを判定する

- 普遍的なことをいうために, 母平均を考える

  標本平均は，あくまでも標本

- 比較対象が与えられているので，検定が簡単 (離れ具合が (既知) 比較 わかりやすい)

 
** 母平均の検定の適用例

- 病気の疑いのあるグループの平均と正常値とを比較して，病気か健康かを判
  定

- 製造している商品の容量が袋に表記されている基準値と異なっていないかを
  確認
  
- 調査した農家の平 均年齢が真の値からズレていないかを検証

** 検定の原理

分布の母平均 μ を仮定，標本平均 \( \overline{X}_{n} \) を計算

真の値なので，よく 起きる(確率が高い)

滅多に起きない区間

- 実験結果が両端に来たら，こ の分布は真の分布ではない
  
  実験結果の平均値が両端に位 置するならば，この分布ではなく 別の分布に
  従っていると考える

** ステップ1:2つの仮説を考える

- 帰無仮説 H0:μ=μ0 :: 
母集団

- 対立仮説 H1:μ≠μ0 ::
  μ=μ0 値均
母集団 母集団
        特定の
標本平
μ0 μ 特定の 標本平
μ0 x ̄
μ0 x ̄
同じ母集団から抽出 (μ0は𝑥 ̄ の真の値)
異なる母集団から抽出 (μ0は𝑥 ̄ の真の値ではない)
値均

*** 対立仮説の内容は3種類

普通はどち らが大きいかはわからないため，両側検定を基本とする

- パターン1 μ≠μ0 :: 両側検定

  どちらが大きくなるかは不明 (とにかく差があることに興味がある)

- パターン2 :μ<μ0  :: 片側検定

  比較値μ0が標本の母平均μより も大きいと仮定できる (あるいは比較値の
  方が小さいことには興味がない)

- パターン3 μ>μ0 :: 片側検定

  比較値μ0が標本の母平均μより も小さいと仮定できる(あるいは比較値の
  方が大きいこ片側検定の方が差があることをいいやすいが，と
  には興味がない)

** ステップ2: 帰無仮説が正しい場合の  標本の位置は?

- μ0を真の値とした母集団から抽出した標本分布(比較対象)

  注:実際にはμ0が既知なので分布を考える必要なし
   
- μを真の値とした母集団から抽出した標本分布 (観測された標本の分布)

  
標本平均 𝑥 ̄
棄却域
離れた値をとるならば帰 無仮説が間違っている 可能性が高い(次掲)
      重なっている (どちらも同じ 母集団)
    棄却域
μ=μ0 帰無仮説の受容域
帰無仮説が正しいなら， 標本平均𝑥 ̄ は比較値μ0と
近い値を取りやすい

  ステップ2の続き:  帰無仮説が間違っている場合は?
 μ0を真の値とした標本分布 (比較対象)
帰無仮説の分布
μを真の値とした標本分布 (観測された標本分布)
対立仮説の分布
異なる母集団から抽出された ので標本分布も離れている
        𝑥 ̄ 𝑥 ̄
帰無仮説が間違っているなら，標本 平均𝑥 ̄ はμ0と離れた値を取りやすい
μ0 μ
   どれぐらい離れていれば帰 無仮説は間違い?

  ステップ3:どこから帰無仮説を棄却する?
    有意水準α/2 注:両側検定では両
側合わせた確率がα
棄却域
任意の有意水準(一般的にα=5%とする)に対応する値を 基準(限界値)として，帰無仮説の是非を判定 (片側検定では片方だけで5%とするので棄却域が広がる)
帰無仮説が正しいとした下 の標本分布
有意水準α/2
 帰無仮説の分布
    μ0 棄却域
𝑥 ̄
     限 界 値
限 界 値

  ステップ4:限界値を求めて  検定統計量(観測された標本平均)と比較する
   正規分布 (中心極限定理より)
有意水準α/ 2=0.025
有意水準α/ 2=0.025
     帰無仮説の分布
    母標準誤差(標本平
均𝑥 ̄ の母標準偏差) μ0
𝑥 ̄
μ0 −1.96σx 受容
𝑥 ̄
𝑥 ̄ 棄却
   μ0 ±1.96σx z分布表から上側確率が
0.025になるz値を読み取る (区間推定と同じ)
μ0 +1.96σx
 これぐらいの差ならば 偶然に観測されるこ とがある(帰無仮説は 間違いとはいえない)
滅多に起きないぐらいの 大きな差なので，別の分 布に従う(帰無仮説は間 違い)→有意差がある

   ステップ4の補足:p
値を使った検定法  (ソフトウェアが必要)
        有意水準α/2
帰無仮説の分布
μ0
有意水準α/2
    p値 2
p値 2
   𝑥 ̄ 実験で観測された標本平均
 限界値
限界値
𝑥 ̄
(検定統計量)
p値:帰無仮説の下で，実験結果(検定統計量)よりも極端な値    が観測される確率 →p値を有意水準αと比較して“p<α”ならば帰無仮説を棄却(有意)

   例 題
A君が大きなテントウムシ(平均体長𝑥 ̄ =11mm)を数匹採集し
た。このテントウムシは新種だろうか?それとも既知の種 (○○テントウ)だろうか?ただし，既知の種の真の体長，つ まり母平均μ0=5mm，母標準誤差σ𝑥 ̄ =2mmとし，種は体長で決
まるとする。
○○テントウ
新種
  (真の体長
解:標本平均𝑥 ̄=11と特定の値μ =5mmとを比較して，その抽出元の
0
(真の体長 μ)
μ0) 母集団の平均にも差があることを「(1標本の)母平均の検定」で
  H :同じ母集団? H :異なる母集団(新種)?
0
1
x ̄ =11mm
   検証します。 μ0=5mm 既知の○○テントウ
比較
A君の見つけたテントウムシ

  例題 続き
手順1:仮説の設定
   H0:μ(𝑥 ̄ =11mm)=μ0(5mm)→新種でない(同じ母集団から抽出)
    H1:μ(𝑥 ̄ =11mm)≠μ0(5mm)→新種である(異なる母集団 から抽出)
手順2の検定統計量の計算は不要 手順3の平均体長が11mm以上の○○テントウが見つかる確率の計算も難 しいので，その珍しさを帰無仮説の分布の位置で判断する(手順4)
手順4:仮説の判定 設定した有意水準(今回は両側5%とする)に対応する限界値を求め，それ と標本平均11mmを比較し，帰無仮説の是非を判定する。 限界値は，(比較対象値)±(有意水準に対応するz値)×母標準誤差なの で，5±1.96×2から，下限値が1.08mm，上限値が8.92mmとなる。 ∴ 標本平均>上限値なので，帰無仮説は棄却してよいだろう(次に図 掲)。

 
